### ISSUE TITLE
Issue with hardcoded switch-case

### ISSUE THREAD

**Issue by karak1974** [knoguchi/mmdb2csv#1]
At the end of the main function the hardcoded values of the switch are outdated.
For example the city MMDB no longer `GeoIP2City.mmdb` because it's `GeoLite2-City.mmdb` now.
I would suggest to keep the file names up to date or find a way to make it dynamic like bool flags(for ex:`--city`, `--country`, etc).

**Comment by knoguchi** [comment]
The GeoIP2City.mmdb is a commercial version that is more accurate than GeoLite2-City.mmdb.   I believe the field layout is identical.   I'd add it like this.
```
case "GeoIP2City.mmdb", "GeoLite2-City.mmdb":
```

mmdb has no database type identifier as far as I know.  The file name is the only key to identify the type.
Maxmind offers GeoLite2 dbs in CSV format.  I suggest the official CSV files.
